basic.forever(function () {
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 0)
    basic.pause(2000)
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 50)
    basic.pause(2000)
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 100)
    basic.pause(2000)
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 150)
    basic.pause(2000)
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 200)
    basic.pause(2000)
    Tinybit.CarCtrlSpeed(Tinybit.CarState.Car_Run, 255)
    basic.pause(5000)
})
basic.forever(function () {
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Red))
    Tinybit.RGB_Car_Big2(255, 255, 255)
    basic.pause(200)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Blue))
    Tinybit.RGB_Car_Big2(159, 43, 45)
    basic.pause(200)
    Tinybit.RGB_Car_Big2(64, 49, 85)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Yellow))
    basic.pause(200)
    Tinybit.RGB_Car_Big2(42, 55, 64)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(200)
    Tinybit.RGB_Car_Big2(59, 255, 100)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.White))
    basic.pause(200)
    Tinybit.RGB_Car_Program().showColor(neopixel.colors(NeoPixelColors.Indigo))
})
